# Generated by Django 5.0.1 on 2024-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_dogs', '0010_alter_feedback_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
