# Generated by Django 5.0.1 on 2024-01-26 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_dogs', '0011_alter_feedback_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_dogs.course')),
            ],
            options={
                'verbose_name_plural': 'about_courses',
            },
        ),
    ]
