# Generated by Django 5.0.1 on 2024-01-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_dogs', '0012_about_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about_course',
            name='text',
        ),
        migrations.AddField(
            model_name='about_course',
            name='course_description',
            field=models.TextField(default='Default Course Description'),
        ),
        migrations.AddField(
            model_name='about_course',
            name='phrase',
            field=models.CharField(default='Default Phrase', max_length=200),
        ),
        migrations.AddField(
            model_name='about_course',
            name='target_audience',
            field=models.CharField(choices=[('beginners', 'Новачки'), ('enthusiasts', 'Любителям'), ('experts', 'Експертам')], default='beginners', max_length=100),
        ),
    ]
