# Generated by Django 5.0.1 on 2024-01-29 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_dogs', '0015_registeredcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='section_photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='section_videos/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_dogs.modulesection')),
            ],
        ),
    ]
